### ISSUE TITLE
Question... CORS issue

### ISSUE THREAD

**Issue by CHBaker** [luixaviles/socket-io-typescript-chat#15]
Hello, I'm building a clone of your app, following along with the blog, and i'm getting this error in my console:

`Failed to load http://http/socket.io/?EIO=3&transport=polling&t=M82Q3LZ: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5050' is therefore not allowed access.`

But in my network tab, everything is coming through as OK 200... 

Any ideas why this is happening? I git cloned this repo, and no errors come up when I run it, and my code looks exactly like yours minus the material style, and I don't have any of the new stuff you added to the project, just what I got from following along with the blog post

**Comment by headwinds** [comment]
@CHBaker Did you fix your problem? that url ```http://http/socket.io/?EIO=3&transport=polling&t=M82Q3LZ``` looks a little strange - double http?! - but beyond that did you try adding [cors to express](https://github.com/expressjs/cors)?

**Comment by luixaviles** [comment]
Just updated client/server code to latest versions. Let me know if you have the same issue.
