### ISSUE TITLE
working on the server 

### ISSUE THREAD

**Issue by headwinds** [luixaviles/socket-io-typescript-chat#17]
@luixaviles when you're working on the server, have you setup a watch script? 

I went through the gulpfile and I don't see the ability to make changes, save, and have the server update.

I did some digging and found this [stackoverflow](https://stackoverflow.com/questions/33748597/how-to-configure-gulp-for-typescript-live-reload-express) thread - as the author describes, it's not perfect but it works. 

So I've installed 'ts-node' and updated your gulpfile to work with this project - and it works which is most of the battle - just want to get your feedback if you have a less hacky solution? 

```
var gulp = require('gulp'),
  nodemon = require('gulp-nodemon'),
  livereload = require('gulp-livereload'),
  ts = require('gulp-typescript');

var tsProject = ts.createProject('tsconfig.json');

gulp.task('typescript', function() {
  console.log('Compiling TypeScript');

  return tsProject
    .src()
    .pipe(tsProject())
    .js.pipe(gulp.dest('./dist'));
});

gulp.task('serve', ['typescript'], function() {
  gulp.watch('./**/*.ts', ['typescript']);

  livereload.listen();
  // make sure you have installed ts-node via npm i ts-node
  nodemon({
    exec: 'ts-node ./src/index.ts',
    ext: 'ts'
  }).on('restart', function() {
    setTimeout(function() {
      console.log('reload!');
      livereload.reload();
    }, 500);
  });
});
```

**Comment by luixaviles** [comment]
Hey @headwinds, trying to be up-to-date on this project. I just updated the client and server to the latest versions available.
Do you want to send a PR with your suggestions and close this issue?

**Comment by headwinds** [comment]
@luixaviles wow I don't even remember adding this comment but I've just sat down with coffee and might as well turn it into code - I'll pull your latest and add the above as a PR - please don't wait another year ;-D
