### ISSUE TITLE
what the code inside index.js?

### ISSUE THREAD

**Issue by gieboyz** [luixaviles/socket-io-typescript-chat#21]
Hi sir, i want to trying make an chatting application inside on my existing application.
i just want to ask to you what the code inside index.js ?? from your Procfile

`web: node server/dist/index.js`

thank you.

**Comment by mac1253** [comment]
Are you asking what it does? 
Im guessing thats the transpiled server code?

**Comment by luixaviles** [comment]
Take a look at Heroku Dev center about [the Procfile](https://devcenter.heroku.com/articles/procfile), it will help to understand the purpose of it.
