### ISSUE TITLE
On the Server side - Cannot GET /

### ISSUE THREAD

**Issue by KarinNiffeler** [luixaviles/socket-io-typescript-chat#22]
First of all, it is a great application! Thank you.

On the client side, everything works fine. I can start the server on localhost:8080 and I see all the conversation of the diverse localhost:4200s in the server terminal. But in the browser localhost:8080 (server) it is written Error: "Cannot GET /". What could be the issue? How can I fix this error?
I have downloaded your files from GitHub and the terminal (server) looks fine (see screenshot).

Many thanks for your help!
Karin
<img width="677" alt="screen shot 2018-08-28 at 22 56 00" src="https://user-images.githubusercontent.com/40627254/44750466-bf7b6c80-ab15-11e8-8c41-12cb3df65c14.png">

**Comment by KarinNiffeler** [comment]
Meanwhile, I have found the bug. If you like to use angular 6 then you will need to add 
(window as any).global = window; to polyfills.ts

https://github.com/socketio/socket.io-client/issues/1206

**Comment by luixaviles** [comment]
I just updated the client and server project with the latest versions available. Please let me know if you still have this issue.
