### ISSUE TITLE
Cannot find name 'Symbol'

### ISSUE THREAD

**Issue by xinthose** [luixaviles/socket-io-typescript-chat#27]
```
C:\node_apps\socket-io-typescript-chat\server>gulp build
[11:31:37] Using gulpfile C:\node_apps\socket-io-typescript-chat\server\gulpfile
.js
[11:31:37] Starting 'build'...
Compiler option 'compileOnSave' requires a value of type boolean.
C:/node_apps/socket-io-typescript-chat/server/node_modules/@types/node/index.d.t
s(6903,88): error TS2304: Cannot find name 'Symbol'.
[11:31:39] TypeScript: 1 semantic error
[11:31:39] TypeScript: emit succeeded (with errors)
[11:31:39] Finished 'build' after 1.89 s
```

**Comment by xinthose** [comment]
You do not browse the server at `http://localhost:8080`, you browse the client at `http://localhost:4200` while your server is running.

**Comment by xinthose** [comment]
Obviously the line is in `tsconfig.json`: ` "compileOnSave": false,`

**Comment by SwapnilSoni1999** [comment]
Have you fixed?

**Comment by AdamShechter9** [comment]
Same issue here.

gulp-cli@2.0.1
node --version
v11.4.0

**Comment by xinthose** [comment]
Gulp still builds fine.  I have not noticed any adverse effects from this error in the project.

**Comment by SwapnilSoni1999** [comment]
For a temp fix I have edited from Library `| Symbol` thing which I don't remember now. 
But I just removed it and it got compiled and working fine. issue is its not in ES6 format and outdated right now.

**Comment by Guttz** [comment]
Same issue and one other: 

/home/rootuser/Documents/angular/socket-io-typescript-chat/server/node_modules/@types/node/perf_hooks.d.ts(275,31): error TS2304: Cannot find name 'Map'.
/home/rootuser/Documents/angular/socket-io-typescript-chat/server/node_modules/@types/node/util.d.ts(117,88): error TS2304: Cannot find name 'Symbol'.

My current config:
node -v
v8.10.0
npm -v
3.5.2

**Comment by dianjvm** [comment]
Just Change the Lib on tsconfig.json
Befor : 
`{
  "files": [
    "src/*.ts",
    "src/model/*.ts"
  ],
  "compilerOptions": {
    "noImplicitAny": true,
    "target": "es5"
  }
}`

After :
`{
  "files": [
    "src/*.ts",
    "src/model/*.ts"
  ],
  "compilerOptions": {
    "noImplicitAny": true,
    "target": "es5",
    "lib": ["es5", "es2015.symbol", "es2015.symbol.wellknown"]
  }
}`

i think this fixed the issue.

**Comment by xinthose** [comment]
I am no longer noticing the issue:
```
C:\node_apps\eds4\server>gulp -v
[08:26:14] CLI version 2.0.1
[08:26:14] Local version 4.0.2
```
