### ISSUE TITLE
always re type username?

### ISSUE THREAD

**Issue by mbtech1177** [luixaviles/socket-io-typescript-chat#34]
how to not always re type username when refresh or reload page ?

thanks

**Comment by jacovinus** [comment]
try saving your user in LocalStorage when creating new user, then deleting it when login out.

**Comment by luixaviles** [comment]
If anyone wants to contribute, it would be great to add a new service to save the user name and keep the username after reloading the page.

**Comment by harshilparmar** [comment]
@luixaviles  can I try?

**Comment by luixaviles** [comment]
Closed by #61
