### ISSUE TITLE
Browser screenshots.

### ISSUE THREAD

**Issue by DAMANgoldberg** [luixaviles/socket-io-typescript-chat#4]
1st one is Firefox 55.0.3 (64-bit) Win 10 Pro 15063.540

![fireshot capture 2 - socket io typescript chat example - https___typescript-chat firebaseapp com_](https://user-images.githubusercontent.com/8891054/30058357-9c539268-9208-11e7-9d24-c61b29904de7.png)

2nd one is Vivaldi 1.11.917.43 (32-bit) same Windows system

![vb-fireshot pro screen capture 321 - socket_io typescript chat example](https://user-images.githubusercontent.com/8891054/30058423-ec99619e-9208-11e7-9b5d-5381e763d3b9.png)

No current clean method of getting the embedded conversation in a screenshot. HTH.

**Comment by DAMANgoldberg** [comment]
Did individual screenshots and combined into a PDF. I can upload the ingredients if requested.
[Typescript chat demo 08052017.pdf](https://github.com/luixaviles/socket-io-typescript-chat/files/1277196/Typescript.chat.demo.08052017.pdf)

**Comment by DAMANgoldberg** [comment]
Did the individual screenshots of the entire conversation as of that point.
![vb-fireshot pro screen capture 326 - socket_io typescript chat example](https://user-images.githubusercontent.com/8891054/30058921-efd31312-920a-11e7-9572-a3fe8d76a526.png)
![vb-fireshot pro screen capture 327 - socket_io typescript chat example](https://user-images.githubusercontent.com/8891054/30058931-f5d61476-920a-11e7-92fd-2ac64abab311.png)
![vb-fireshot pro screen capture 328 - socket_io typescript chat example](https://user-images.githubusercontent.com/8891054/30058939-faf4396a-920a-11e7-9529-5d6562796789.png)
![vb-fireshot pro screen capture 329 - socket_io typescript chat example](https://user-images.githubusercontent.com/8891054/30058944-fec65140-920a-11e7-8b5a-f1d7a7f65d06.png)

**Comment by DAMANgoldberg** [comment]
Apologies, still new to this GitHub thing.

**Comment by redraushan** [comment]
@DAMANgoldberg, I don't see any problem in my firefox 55.0.2 (64-bit) ubuntu. 
Maybe try clearing your browser cache or hard refresh by pressing  `"ctrl + shift + r`
See the below screenshot.

![screenshot from 2017-09-06 17-30-36](https://user-images.githubusercontent.com/12084473/30110926-7da3e8be-9329-11e7-8914-82ecdda820a0.png)


If that works for you then close the issue.

**Comment by DAMANgoldberg** [comment]
Here is my latest attempt: did a hard refresh of cache.

![fireshot capture 5 - socket io typescript chat example - https___typescript-chat firebaseapp com_](https://user-images.githubusercontent.com/8891054/30121586-1a5bb388-92fa-11e7-98af-f4df7037ff00.png)

**Comment by DAMANgoldberg** [comment]
With a fresh install of Firefox 55.0.3 (64-bit) on Windows 10, now it looks right.

![screenshot-2017-9-7 socket io typescript chat example](https://user-images.githubusercontent.com/8891054/30151937-7652a31a-937f-11e7-9f3f-b0f1ebef2171.png)

**Comment by DAMANgoldberg** [comment]
Now it works, and the issue is closed. Herbert H Dupree II (@MCHerbieD)Literary Nirvana 
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Literary Nirvana
 Sometimes a Fertile Mind can bear fruit.  |   |

  |

  |

 
FREE YOUR MIND AND THE REST WILL FOLLOW; LOVE WILL WIN! 

    On Wednesday, September 6, 2017 8:04 AM, Raushan Sharma <notifications@github.com> wrote:
 

 @DAMANgoldberg, I don't see any problem in my firefox 55.0.2 (64-bit) ubuntu.
Maybe try clearing your browser cache or hard refresh by pressing "ctrl + shift + r
See the below screenshot.If that works for you then close the issue.—
