### ISSUE TITLE
socket.io-client dependency version mismatch

### ISSUE THREAD

**Issue by michaelkrone** [luixaviles/socket-io-typescript-chat#5]
It seems `socket.io-client` is only available in the client project because karma defines it as a dependency. This will not allow to explicit define the socket.io-client version to be used. 
Additionally, the server defines the socket.io dependency as `socket.io": "~2.0.3`. karma@1.7.1 is using `socket.io-client@1.7.3`, which already is a major version mismatch.

Maybe the client should use the socket.io-client the server is serving, or at least use socket.io as a defined dependency in the clients package.json

**Comment by luixaviles** [comment]
Hi @michaelkrone. I think now we have right versions on the client/server side:

- Client: `"socket.io": "~2.0.3"` and `"@types/socket.io-client": "~1.4.29"`
- Server: ` "socket.io": "~2.0.3"` and `"@types/socket.io": "~1.4.29"`

Thanks.
